package com.verificador.catalogos.utils;

public interface Constantes {
	
	String CONTEXT_ROOT = "/";
	String CONTEXT_PATH_MARCAS = "marcas";
	String CONTEXT_PATH_ERRORES = "errores";
	String CONTEXT_PATH_SISTEMA = "sistemas";
	String CONTEXT_PATH_CATALOGO_ERROR = "catalogo-errores";
	String CONTEXT_PATH_GASOLINERAS = "gasolineras";
	String CONTEXT_PATH_BOMBAS = "bombas";
	String CONTEXT_PATH_TANQUES = "tanques";
	String CONTEXT_MARCAS = CONTEXT_ROOT+CONTEXT_PATH_MARCAS;
	String CONTEXT_ID = CONTEXT_ROOT+"{id}";
	String CONTEXT_PDF = "pdf";
	String CONTEXT_ID_GASOLINERA = CONTEXT_ROOT+"{idGasolinera}";
	String CONTEXT_GASOLINERAS = CONTEXT_ID+CONTEXT_ROOT+CONTEXT_PATH_GASOLINERAS;
	String CONTEXT_GASOLINERA_ID = CONTEXT_ID+CONTEXT_ROOT+CONTEXT_PATH_GASOLINERAS+CONTEXT_ID_GASOLINERA;
	String CONTEXT_BOMBAS = CONTEXT_ID+CONTEXT_ROOT+CONTEXT_PATH_GASOLINERAS+CONTEXT_ID_GASOLINERA+CONTEXT_ROOT+CONTEXT_PATH_BOMBAS;
	String CONTEXT_TANQUES = CONTEXT_ID+CONTEXT_ROOT+CONTEXT_PATH_GASOLINERAS+CONTEXT_ID_GASOLINERA+CONTEXT_ROOT+CONTEXT_PATH_TANQUES;
	String CONTEXT_ERRORES = CONTEXT_ROOT + CONTEXT_PATH_ERRORES;
	String CONTEXT_ERRORES_SISTEMA = CONTEXT_ID + CONTEXT_ROOT + CONTEXT_PATH_SISTEMA;
	String CONTEXT_CATALOGO_ERRORES = CONTEXT_ROOT + CONTEXT_PATH_CATALOGO_ERROR;
	String CONTEXT_GASOLINERA_PDF = CONTEXT_ID+CONTEXT_ROOT+CONTEXT_PDF;
	
	String CODE_SUCCESFULL = "200";
	String CODE_BAD_REQUEST = "400";
	String CODE_NOT_FOUND = "404";
	
	String CROSSORIGIN = "https://verifigas-demo-ui.azurewebsites.net";
	String DATE_FORMAT = "yyyy-MM-dd:hh:mm:ss";
}
