server:
  port: 8080
spring:
  application:
    name: verifigas-demo-core
  datasource:
    url: jdbc:postgresql://gasolineras.postgres.database.azure.com/gasolinera
    username: superUsuario@gasolineras
    password: Administrador1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect